var subjectObject = {
  UNGA: [
    "Afghanistan",
    "Albania",
    "Algeria",
    "Andorra",
    "Angola",
    "Argentina",
    "Armenia",
    "Australia",
    "Austria",
    "Bahrain",
    "Bangladesh",
    "Belarus",
    "Belgium",
    "Belize",
    "Botswana",
    "Brazil",
    "Bulgaria",
    "Burkina faso",
    "Canada",
    "Central African Republic",
    "Chile",
    "China",
    "Colombia",
    "Cuba",
    "Czech Republic",
    "Denmark",
    "Egypt",
    "Estonia",
    "Ethiopia",
    "Finland",
    "France",
    "Germany",
    "Greece",
    "Hungary",
    "Iceland",
    "Indonesia",
    "Iraq",
    "Ireland",
    "Islamic Republic of Iran",
    "Israel",
    "Italy",
    "Japan",
    "Jordan",
    "Kenya",
    "Kuwait",
    "Latvia",
    "Lebanon",
    "Libya",
    "Lithuania",
    "Malawi",
    "Malaysia",
    "Maldives",
    "Moldova",
    "Mongolia",
    "Morocco",
    "Myanmar",
    "Netherlands",
    "New Zealand",
    "Nigeria",
    "Norway",
    "Oman",
    "Pakistan",
    "Palestine(O)",
    "Philippines",
    "Poland",
    "Portugal",
    "Romania",
    "Russian Federation",
    "San Marino",
    "Saudi Arabia",
    "Sierra leone",
    "Singapore",
    "Slovakia",
    "Slovenia",
    "Spain",
    "Sri Lanka",
    "Sudan",
    "Sweden",
    "Syrian arab republic",
    "Tajikistan",
    "Turkey",
    "Ukraine",
    "United Kingdom",
    "United States Of America",
    "Uzbekistan",
    "Venezuela",
    "Vietnam",
    "Yemen",
  ],
  UNCSW: [
    "Afghanistan",
    "Algeria",
    "Argentina",
    "Armenia",
    "Australia",
    "Austria",
    "Bangladesh",
    "Belarus",
    "Brazil",
    "Colombia",
    "Comoros",
    "Congo",
    "Cuba",
    "Denmark",
    "Dominican",
    "Republic",
    "Ecuador",
    "Equatorial Guinea",
    "Germany",
    "Ghana",
    "Haiti",
    "India",
    "Iraq",
    "Israel",
    "Japan",
    "Kenya",
    "Latvia",
    "Malaysia",
    "Mexico",
    "Mongolia",
    "Morocco",
    "Nicaragua",
    "Nigeria",
    "Philippines",
    "Republic of Korea",
    "Russian Federation",
    "Saudi Arabia",
    "Senegal",
    "Somalia",
    "South Africa",
    "Switzerland",
    "Togo",
    "Turkey",
    "Turkmenistan",
    "United States",
    "Zambia",
  ],
  
  UNHRC: [
    "Afghanistan (O)",
    "Argentina",
    "Armenia",
    "Australia (O)",
    "Austria",
    "Bahamas",
    "Bahrain",
    "Bangladesh",
    "Barbados (O)",
    "Belgium (O)",
    "Bolivia",
    "Brazil",
    "Bulgaria",
    "Burkina Faso",
    "Canada (O)",
    "Cameroon",
    "China",
    "Côte d’Ivoire",
    "Chad(O)",
    "Chile (O)",
    "Colombia (O)",
    "Costa Rica (O)",
    "Croatia (O)",
    "Cuba",
    "Czech Republic",
    "Democratic People's Republic of Korea (O)",
    "Democratic Republic of the Congo (O)",
    "Denmark",
    "Eritrea",
    "Egypt (O)",
    "Fiji",
    "Finland (O)",
    "France",
    "Germany",
    "Gabon",
    "Hungary (O)",
    "Iceland (O)",
    "India",
    "Indonesia",
    "Islamic Republic of Iran (O)",
    "Italy",
    "Jamaica (O)",
    "Japan",
    "Kenya (O)",
    "Libya",
    "Lithuania (O)",
    "Luxembourg (O)",
    "Macedonia (O)",
    "Malawi",
    "Marshall Islands",
    "Malaysia (O)",
    "Mexico (O)",
    "Myanmar (O)",
    "Namibia",
    "Nepal",
    "Netherlands",
    "New Zealand (O)",
    "Norway (O)",
    "Pakistan",
    "Paraguay (O)",
    "Peru (O)",
    "Philippines",
    "Poland",
    "Portugal (O)",
    "Qatar (O)",
    "Republic of Korea",
    "Romania (O)",
    "Russian Federation",
    "Senegal",
    "Saudi Arabia (O)",
    "Slovakia (O)",
    "Solomon Islands (O)",
    "Somalia",
    "South Africa (O)",
    "Spain (O)",
    "Sri Lanka (O)",
    "Sudan",
    "Sweden (O)",
    "Switzerland (O)",
    "Syrian Arab Republic (O)",
    "Togo",
    "Thailand (O)",
    "Turkey (O)",
    "Ukraine",
    "United Kingdom",
    "United States of America (O)",
    "Uruguay",
    "Uzbekistan",
    "Venezuela (Bolivarian Republic of)",
  ],
  
  
  AIPPM: ["Narendra Modi",
  "Rajanath Singh",
  "Nirmala Sitharaman",
  "Smriti Irani",
  "Maneka Gandhi",
  "Amit Shah",
  "Jyotiraditya Scindia",
  "Nitin Gadkari",
  "Ravi Shankar Prasad",
  "Dr Harsh Vardhan",
  "Subramanyam Jaishankar",
  "Vasundhara Raje",
  "Captain Amarinder Singh",
  "Kiren Rijiju",
  "Arjun Ram Meghwal",
  "Himanta Biswa Sarma",
  "Pramod Sawant",
  "Bhupendrabhai Patel",
  "Basavaraj Bommai",
  "Shivraj Singh Chouhan",
  "Manik Saha",
  "Pushkar Singh Dhami",
  "Dharmendra Pradhan",
  "Ashvini Vaishnaw",
  "Mukhtar Abbas Naqvi",
  "Hardeep Singh Puri",
  "N. Biren Singh",
  "Sonia Gandhi",
  "Rahul Gandhi",
  "Ambika Soni",
  "Dr Shashi Tharoor",
  "Sachin Pilot",
  "Meira Kumar",
  "Salman Khurshid",
  "Dr Manmohan Singh",
  "Gaurav Gogoi",
  "Bhupesh Baghel",
  "Sukhvinder Singh Sukhu",
  "Ashok Gehlot",
  "Adhir Ranjan Chowdhury",
  "Karti P Chidambaram",
  "Manish Tewari",
  "Arvind Kejriwal",
  "Raghav Chadha",
  "Sanjay Singh",
  "Bhagwant Mann",
  "Asaddudin Owaisi",
  "N. Rangaswamy",
  "Mamata Banerjee",
  "Mimi Chakraborty",
  "Mahua Moitra",
  "Abhishek Banerjee",
  "Chandra Prakash Choudhary",
  "Anupriya Patel",
  "Kumari Mayawati",
  "Satish Mishra",
  "Afzal Ansari",
  "Kunwar Danish Ali",
  "K P Reddy",
  "Bhartruhari Mahtab",
  "Naveen Patnaik",
  "Sitaram Yechury",
  "Brinda Karat",
  "Pinarayi Vijayan",
  "Dayanidhi Maran",
  "M. K. Stalin",
  "Naba Kumar Sarania",
  "Dr. Farooq Abdullah",
  "Kaushalendra Kumar",
  "Nitish Kumar",
  "Chirag Paswan",
  "Raj Thackeray",
  "Zoramthanga",
  "Agatha Sangma",
  "Conrad Sangma",
  "Sharad Pawar",
  "Ajit Pawar",
  "Praful Patel",
  "Neiphiu Rio",
  "Tejashvi Yadav",
  "Misa Bharti",
  "Rabri Devi",
  "Manoj Jha",
  "Mehboob Ali Kaiser",
  "Hanuman Beniwal",
  "N K Premachandran",
  "Akhilesh Yadav",
  "Ram Gopal Yadav",
  "Harsimrat Kaur Badal",
  "Sukhbir Singh Badal",
  "Sanjay Raut",
  "Uddhav Thackeray",
  "Vinayak Raut",
  "Eknath Shinde",
  "Prem Singh Tamang",
  "Indra Hang Subba",
  "Yogendra Yadav",
  "Derek O'Brien",
  "Y. S. Jagan Mohan Reddy",
  "Ghulam Nabi Azad"],
};

window.onload = function () {
  var one_1 = document.getElementById("one-1");
  var one_2 = document.getElementById("one-2");

  var two_1 = document.getElementById("two-1");
  var two_2 = document.getElementById("two-2");

  var three_1 = document.getElementById("three-1");
  var three_2 = document.getElementById("three-2");

  for (var x in subjectObject) {
    one_1.options[one_1.options.length] = new Option(x, x);
  }

  one_1.onchange = function () {
    //empty Chapters- and Topics- dropdowns
    one_2.length = 1;
    //display correct values
    for (var y in subjectObject[this.value]) {
      var z = subjectObject[this.value][y];
      one_2.options[one_2.options.length] = new Option(z, z);
    }
  };

  for (var x in subjectObject) {
    two_1.options[two_1.options.length] = new Option(x, x);
  }

  two_1.onchange = function () {
    //empty Chapters- and Topics- dropdowns
    two_2.length = 1;
    //display correct values
    for (var y in subjectObject[this.value]) {
      var z = subjectObject[this.value][y];
      two_2.options[two_2.options.length] = new Option(z, z);
    }
  };


  for (var x in subjectObject) {
    three_1.options[three_1.options.length] = new Option(x, x);
  }

  three_1.onchange = function () {
    //empty Chapters- and Topics- dropdowns
    three_2.length = 1;
    //display correct values
    for (var y in subjectObject[this.value]) {
      var z = subjectObject[this.value][y];
      three_2.options[three_2.options.length] = new Option(z, z);
    }
  };
};
